#!/bin/bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain="$1"
subdomain="$2"

function get_record_info() {
    local sub="$1"
    local type="$2"

    local result=$(dig "$sub"."$domain" | awk '/ANSWER SECTION/ {getline; print}')

    echo "The subdomain $sub is a $type record and points to $result"
}

if [[ -z "$subdomain" ]]; then
    get_record_info "www" "A"
    get_record_info "lb-01" "A"
    get_record_info "web-01" "A"
    get_record_info "web-02" "A"
else
    get_record_info "$subdomain" "A"
fi
